import { AlertTriangle, CheckCircle2, Plus } from 'lucide-react';

import {
  addQualityAction,
  addRrrAttachment,
  addRrrAttendance,
  addRrrEvidence,
  addRrrOpenItem,
  addRrrRevision,
  addRrrSignatory,
  addRrrTag,
  saveRrrReadinessAction,
} from '@/app/actions/quality-records';
import { ActionTracker } from '@/components/quality-records/action-tracker';
import { StatusBadge } from '@/components/shared/status-badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';
import type { Tables } from '@/types/database';

type ServerFormAction = (formData: FormData) => Promise<{ success: boolean; message: string }>;
const asFormAction = (action: ServerFormAction) => action as unknown as (formData: FormData) => Promise<void>;

type Workspace = {
  readiness: Tables<'rrr_readiness_controls'>[]; tags: Tables<'rrr_commissioning_tags'>[]; openItems: Tables<'rrr_open_items'>[];
  evidence: Tables<'rrr_evidence'>[]; attendance: Tables<'rrr_attendance'>[]; signatories: Tables<'rrr_signatories'>[];
  revisions: Tables<'rrr_submission_revisions'>[]; attachments: Tables<'rrr_linked_attachments'>[]; actions: Tables<'quality_record_actions'>[];
};

export function RrrWorkspace({ rrr, workspace }: { rrr: Tables<'rrr_records'>; workspace: Workspace }) {
  const rr4 = workspace.readiness.find((row) => row.control_level.startsWith('RR-4'));
  const blockers = workspace.openItems.filter((row) => row.status !== 'Closed' && ['P1','P2'].includes(row.priority));
  const declarationReady = rrr.room_complete && rrr.no_open_p1_p2_items && rrr.declaration_complete && rrr.room_secured_under_control && rrr.doors_installed_locked && rrr.access_retained_by_authorized_person && rrr.permit_sleeve_fitted && rrr.loto_applied && rrr.live_warning_notices_fitted && rrr.life_safety_provisions_in_place && rrr.cleanliness_dust_control_maintained;
  const gateBlocked = !rr4 || rr4.percent_complete < 100 || rr4.open_actions_count > 0 || blockers.length > 0 || !declarationReady;
  return <div className="space-y-4">
    <div className={`flex items-start gap-3 rounded-xl border p-4 ${gateBlocked ? 'border-red-300 bg-red-50 text-red-900' : 'border-emerald-300 bg-emerald-50 text-emerald-900'}`}>{gateBlocked ? <AlertTriangle className="mt-0.5 size-5 shrink-0" /> : <CheckCircle2 className="mt-0.5 size-5 shrink-0" />}<div><p className="font-semibold">RR-4 life safety and LOTO gate: {gateBlocked ? 'Blocked' : 'Complete'}</p><p className="mt-1 text-sm">{gateBlocked ? 'The room cannot be treated as released for commissioning or energization while RR-4 or any P1/P2 blocker remains incomplete.' : 'The hard gate is complete. Engineer, CxA and Employer decisions must still be recorded separately.'}</p></div></div>
    <Section title="Readiness declaration · RR-1 to RR-4"><Table><TableHeader><TableRow><TableHead>Control level</TableHead><TableHead>Responsible</TableHead><TableHead>% complete</TableHead><TableHead>Open actions</TableHead><TableHead>Checklist reference</TableHead><TableHead /></TableRow></TableHeader><TableBody>{workspace.readiness.map((row) => <TableRow key={row.id} className={row.control_level.startsWith('RR-4') ? 'bg-red-50/60' : undefined}><TableCell className="max-w-sm whitespace-normal font-medium">{row.control_level}</TableCell><TableCell colSpan={5}><form action={asFormAction(saveRrrReadinessAction)} className="grid min-w-[620px] grid-cols-[1fr_100px_100px_1fr_auto] gap-2"><input type="hidden" name="id" value={row.id} /><input type="hidden" name="rrr_id" value={rrr.id} /><Input name="responsible" defaultValue={row.responsible ?? ''} placeholder="Responsible" /><Input name="percent_complete" type="number" min={0} max={100} defaultValue={row.percent_complete} /><Input name="open_actions_count" type="number" min={0} defaultValue={row.open_actions_count} /><Input name="checklist_reference" defaultValue={row.checklist_reference ?? ''} placeholder="Checklist ref." /><Button size="sm" type="submit">Save</Button></form></TableCell></TableRow>)}</TableBody></Table></Section>
    <div className="grid gap-4 xl:grid-cols-2">
      <Section title="Commissioning tag status">
        {workspace.tags.length ? <SimpleTable headers={['Tag type','Asset / equipment','Facility / grid status','CxA sign-off','Reference','Status']} rows={workspace.tags.map((r) => [r.tag_type,r.asset_equipment,r.facility_grid_status,r.cxa_signoff_date,r.reference,r.status])} /> : <EmptyText text="No L2A, L2B or conditional yellow tag rows recorded." />}
        <details className="border-t p-4"><summary className="cursor-pointer text-sm font-medium text-primary"><Plus className="mr-1 inline size-4" />Add commissioning tag</summary><form action={asFormAction(addRrrTag)} className="mt-4 grid gap-3"><input type="hidden" name="rrr_id" value={rrr.id} /><select name="tag_type" className="h-9 rounded-lg border bg-background px-2" required>{['L2A RED TAG','L2B YELLOW TAG','CONDITIONAL YELLOW TAG / CYT'].map((v) => <option key={v}>{v}</option>)}</select><Input name="asset_equipment" placeholder="Asset / equipment" /><Input name="facility_grid_status" placeholder="Facility / grid status" /><Input name="cxa_signoff_date" type="date" /><Input name="reference" placeholder="Reference" /><Input name="status" placeholder="Status" /><Button type="submit">Add tag</Button></form></details>
      </Section>
      <Section title="Attendance">
        {workspace.attendance.length ? <SimpleTable headers={['Group','Role','Required','Attended','Name']} rows={workspace.attendance.map((r) => [r.attendance_group,r.attendee_role,r.required ? 'Yes':'No',r.attended ? 'Yes':'No',r.attendee_name])} /> : <EmptyText text="No external or SERBAN attendance rows recorded." />}
        <details className="border-t p-4"><summary className="cursor-pointer text-sm font-medium text-primary"><Plus className="mr-1 inline size-4" />Add attendee</summary><form action={asFormAction(addRrrAttendance)} className="mt-4 grid gap-3"><input type="hidden" name="rrr_id" value={rrr.id} /><select name="attendance_group" className="h-9 rounded-lg border bg-background px-2" required><option>External</option><option>SERBAN</option></select><select name="attendee_role" className="h-9 rounded-lg border bg-background px-2" required>{['Employer','Engineer','Commissioning Agent (CxA)','DCC Representative','QA/QC Manager','Site Manager','Commissioning / MEP Manager'].map((v) => <option key={v}>{v}</option>)}</select><Input name="attendee_name" placeholder="Attendee name" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="required" defaultChecked />Required</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="attended" />Attended</label><Button type="submit">Add attendee</Button></form></details>
      </Section>
    </div>
    <Section title="Open items"><SimpleTable headers={['No','Reference','Type','Description','Priority','Raised by','Target','Status']} rows={workspace.openItems.map((r) => [r.item_number,r.reference,r.reference_type,r.description,r.priority,r.raised_by,r.target_date,r.status])} /><details className="border-t p-4"><summary className="cursor-pointer text-sm font-medium text-primary"><Plus className="mr-1 inline size-4" />Add open item</summary><form action={asFormAction(addRrrOpenItem)} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="rrr_id" value={rrr.id} /><Input name="item_number" placeholder="Item number" required /><Input name="reference" placeholder="Reference" /><select name="reference_type" className="h-9 rounded-lg border bg-background px-2"><option value="">Reference type</option>{['IRL','WIR','MIR','SOR','SNR','NCR'].map((v) => <option key={v}>{v}</option>)}</select><select name="priority" className="h-9 rounded-lg border bg-background px-2" required>{['P1','P2','P3','P4'].map((v) => <option key={v}>{v}</option>)}</select><Textarea name="description" placeholder="Description" required className="sm:col-span-2" /><Input name="raised_by" placeholder="Raised by" /><Input name="target_date" type="date" /><select name="status" className="h-9 rounded-lg border bg-background px-2"><option>Open</option><option>Closed</option><option>Disputed</option></select><select name="linked_record_type" className="h-9 rounded-lg border bg-background px-2"><option value="">External reference only</option><option>WIR</option><option>MIR</option><option>NCR</option><option>SOR</option></select><Input name="linked_record_id" placeholder="Internal record UUID (optional)" /><Button type="submit">Add open item</Button></form></details></Section>
    <Section title="Supporting evidence"><SimpleTable headers={['Evidence type','Reference','Date','Uploaded metadata','Approved','Linked record']} rows={workspace.evidence.map((r) => [r.evidence_type,r.reference,r.evidence_date,r.uploaded ? 'Yes':'No',r.approved ? 'Yes':'No',r.linked_record_type])} /><details className="border-t p-4"><summary className="cursor-pointer text-sm font-medium text-primary"><Plus className="mr-1 inline size-4" />Add evidence reference</summary><form action={asFormAction(addRrrEvidence)} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="rrr_id" value={rrr.id} /><select name="evidence_type" className="h-9 rounded-lg border bg-background px-2" required>{['WIR','MIR / MRIR','L2A checklist / test pack','L2B static test report','MCCL','NCR / SNR / punch status','As-built mark-up / schematic','Asset data / equipment list','Photographic record','Deep clean / white-glove inspection'].map((v) => <option key={v}>{v}</option>)}</select><Input name="reference" placeholder="Document / evidence reference" required /><Input name="evidence_date" type="date" /><select name="linked_record_type" className="h-9 rounded-lg border bg-background px-2"><option value="">External reference only</option><option>WIR</option><option>MIR</option><option>NCR</option><option>SOR</option></select><Input name="linked_record_id" placeholder="Internal record UUID (optional)" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="uploaded" />Uploaded metadata confirmed</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="approved" />Approved</label><Button type="submit">Add evidence</Button></form></details></Section>
    <ActionTracker rows={workspace.actions} projectId={rrr.project_id} parentType="RRR" parentId={rrr.id} addAction={addQualityAction} />
    <div className="grid gap-4 xl:grid-cols-2">
      <Section title="Contractor signatories">{workspace.signatories.length ? <SimpleTable headers={['Role','Name','Date','Signature status','Reference']} rows={workspace.signatories.map((r) => [r.role,r.name,r.signed_date,r.signature_status,r.signature_reference])} /> : <EmptyText text="Prepared by QA/QC, Site Manager and Commissioning / MEP Manager signatories have not been recorded." />}<details className="border-t p-4"><summary className="cursor-pointer text-sm font-medium text-primary"><Plus className="mr-1 inline size-4" />Add signatory</summary><form action={asFormAction(addRrrSignatory)} className="mt-4 grid gap-3"><input type="hidden" name="rrr_id" value={rrr.id} /><select name="role" className="h-9 rounded-lg border bg-background px-2" required>{['Prepared by QA/QC','Site Manager','Commissioning / MEP Manager'].map((v) => <option key={v}>{v}</option>)}</select><Input name="name" placeholder="Name" /><Input name="signed_date" type="date" /><Input name="signature_status" placeholder="Signature status" /><Input name="signature_reference" placeholder="Signature reference" /><Button type="submit">Add signatory</Button></form></details></Section>
      <Section title="Linked attachments metadata">{workspace.attachments.length ? <SimpleTable headers={['Type','Document / evidence ref.','Rev','Date','Originator','Submission rev.','Status']} rows={workspace.attachments.map((r) => [r.attachment_type,r.document_evidence_reference,r.revision,r.attachment_date,r.originator,r.linked_submission_revision,r.status])} /> : <EmptyText text="No attachment metadata recorded. Source files are not stored by import." />}<details className="border-t p-4"><summary className="cursor-pointer text-sm font-medium text-primary"><Plus className="mr-1 inline size-4" />Add attachment metadata</summary><form action={asFormAction(addRrrAttachment)} className="mt-4 grid gap-3"><input type="hidden" name="rrr_id" value={rrr.id} /><Input name="attachment_type" placeholder="Attachment type" required /><Input name="document_evidence_reference" placeholder="Document / evidence reference" required /><Input name="revision" placeholder="Revision" /><Input name="attachment_date" type="date" /><Input name="originator" placeholder="Originator" /><Input name="linked_submission_revision" placeholder="Submission revision, e.g. R0.1" /><Input name="status" placeholder="Status" /><Button type="submit">Add metadata</Button></form></details></Section>
    </div>
    <Section title="Submission revision history"><SimpleTable headers={['Submission rev.','Submitted','Returned','Transmittal','Source / reason','Revised by','Status']} rows={workspace.revisions.map((r) => [r.submission_revision,r.submitted_date,r.returned_date,r.submission_transmittal_reference,r.source_reason,r.revised_by,r.status])} /><details className="border-t p-4"><summary className="cursor-pointer text-sm font-medium text-primary"><Plus className="mr-1 inline size-4" />Append submission revision</summary><form action={asFormAction(addRrrRevision)} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="rrr_id" value={rrr.id} /><Input name="submission_revision" placeholder="R0.1" required /><Input name="submitted_date" type="date" /><Input name="returned_date" type="date" /><Input name="submission_transmittal_reference" placeholder="Submission / transmittal ref." /><Textarea name="source_reason" placeholder="Source / reason" required className="sm:col-span-2" /><Input name="revised_by" placeholder="Revised by" /><Input name="status" placeholder="Status" required /><Button type="submit">Append revision</Button></form></details></Section>
  </div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <Card className="gap-0 overflow-hidden py-0"><CardHeader className="border-b bg-slate-800 px-4 py-3"><CardTitle className="text-xs uppercase tracking-[0.11em] text-white">{title}</CardTitle></CardHeader><CardContent className="p-0">{children}</CardContent></Card>; }
function SimpleTable({ headers, rows }: { headers: string[]; rows: (string | number | boolean | null)[][] }) { if (!rows.length) return <EmptyText text="No rows recorded." />; return <div className="overflow-x-auto"><Table><TableHeader><TableRow>{headers.map((h) => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row, i) => <TableRow key={i}>{row.map((value, j) => <TableCell key={j} className={j === 3 && typeof value === 'string' ? 'max-w-sm whitespace-normal' : undefined}>{typeof value === 'string' && ['Open','Closed','Verified','In Progress','Disputed'].includes(value) ? <StatusBadge status={value} /> : value === null || value === '' ? 'Not provided' : String(value)}</TableCell>)}</TableRow>)}</TableBody></Table></div>; }
function EmptyText({ text }: { text: string }) { return <p className="p-5 text-sm leading-6 text-muted-foreground">{text}</p>; }
