import { ArrowLeft, Database, FileLock2, GitBranch, Info, LockKeyhole, Scale } from 'lucide-react';
import Link from 'next/link';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { procoreReference } from '@/lib/procore/reference';
import type { Eas6bSegmentRule, ProcoreMasterCode } from '@/types/procore';

export const dynamic = 'force-dynamic';

export default function NamingConventionPage() {
  const allOfficialSegments = [...procoreReference.eas6b.coreSegments, ...procoreReference.eas6b.electronicFilenameSuffixSegments];
  const comparison = procoreReference.patternComparison;
  const groups: { title: string; description: string; items: ProcoreMasterCode[] }[] = [
    { title: 'Projects', description: 'Source project label with the dominant Procore Name prefix.', items: procoreReference.projects },
    { title: 'Document types', description: 'Type values observed in the Procore export.', items: procoreReference.documentTypes },
    { title: 'Disciplines', description: 'Discipline codes and user-facing labels.', items: procoreReference.disciplines },
    { title: 'Originators', description: 'Originator codes present in the source.', items: procoreReference.originators },
    { title: 'Volume / Systems', description: 'Values from the Volume / System column.', items: procoreReference.volumesSystems },
    { title: 'Source locations', description: 'Values from the Procore Location column.', items: procoreReference.locations },
    { title: 'Naming level + area segments', description: 'Combined Segment 5 values observed in structured Names.', items: procoreReference.namingLocationSlots },
    { title: 'Classifications', description: 'Classification values from the export.', items: procoreReference.classifications },
    { title: 'Statuses', description: 'Workflow outcome codes displayed with labels.', items: procoreReference.statuses },
    { title: 'Revisions', description: 'Every revision value observed in the source.', items: procoreReference.revisionPatterns },
    { title: 'Project stages', description: 'Project Stage master values.', items: procoreReference.projectStages },
  ];

  return (
    <div className="mx-auto flex w-full max-w-[1600px] flex-col gap-5">
      <div><Button nativeButton={false} variant="ghost" size="sm" className="-ml-2 mb-2" render={<Link href="/documents" />}><ArrowLeft />Document register</Button><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-primary"><LockKeyhole className="size-3.5" />Read-only configuration</div><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-[30px]">EAS-6-B and Procore naming convention</h1><p className="mt-1.5 max-w-4xl text-sm leading-6 text-muted-foreground">Official segment composition comes from EAS-6-B v2025-03. Project-specific values and exceptions come from the 205-row Procore export. Rules cannot be edited at this stage.</p></div>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><GitBranch className="size-4 text-primary" />Eight-segment document reference</CardTitle></CardHeader><CardContent><div className="flex flex-wrap items-center gap-2">{procoreReference.eas6b.coreSegments.map((segment, index) => <div key={segment.key} className="contents">{index ? <span className="font-mono text-muted-foreground">–</span> : null}<SegmentChip segment={segment} /></div>)}</div><div className="mt-5 rounded-lg border bg-muted/35 p-3 text-xs leading-5 text-muted-foreground"><Info className="mr-2 inline size-4 text-primary" />Segments 4 and 5 are composite. Their source fields are concatenated inside the segment, without another hyphen. The full official electronic filename has four further segments: Title, Project Phase, Milestone/Purpose, and Revision.</div><div className="mt-5 grid gap-3 md:grid-cols-4"><Evidence label="Core document reference" value="8 segments" /><Evidence label="Full electronic filename" value="12 segments" /><Evidence label="Printed drawing number" value={procoreReference.eas6b.printedDrawingPattern} /><Evidence label="Separator" value="Hyphen (-)" /></div></CardContent></Card>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileLock2 className="size-4 text-primary" />Official segment matrix</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1050px] border-separate border-spacing-0 text-left text-xs"><thead><tr>{['Segment', 'Name', 'Source fields combined inside segment', 'Required', 'Applies to'].map((label) => <th key={label} className="border-b bg-muted/50 px-3 py-2.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</th>)}</tr></thead><tbody>{allOfficialSegments.map((segment) => <tr key={`${segment.position}-${segment.key}`} className="align-top"><td className="border-b px-3 py-3 font-mono font-semibold text-primary">{segment.position}</td><td className="border-b px-3 py-3 font-medium">{segment.name}</td><td className="border-b px-3 py-3 text-muted-foreground">{segment.sourceFields.join(' + ')}{segment.optionalFields.length ? <span className="mt-1 block text-amber-700">Optional subfield: {segment.optionalFields.join(', ')}</span> : null}</td><td className="border-b px-3 py-3">{segment.mandatory ? 'Mandatory' : 'Optional'}</td><td className="border-b px-3 py-3 text-muted-foreground">{segment.appliesTo.join(', ')}</td></tr>)}</tbody></table></div></CardContent></Card>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Scale className="size-4 text-primary" />Document-type segment rules</CardTitle></CardHeader><CardContent><div className="grid gap-3 lg:grid-cols-2">{procoreReference.eas6b.documentTypeRules.map((rule) => <div key={rule.pattern} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">{rule.pattern}</p><span className="font-mono text-[10px] text-primary">{rule.typeCodes.join(', ')}</span></div><p className="mt-3 text-xs leading-5"><strong>Segment 4:</strong> <span className="text-muted-foreground">{rule.segment4Rule}</span></p><p className="mt-1 text-xs leading-5"><strong>Segment 5:</strong> <span className="text-muted-foreground">{rule.segment5Rule}</span></p><p className="mt-2 text-[10px] text-muted-foreground">Authority: {rule.authority}</p></div>)}</div></CardContent></Card>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Scale className="size-4 text-primary" />Every distinct Procore number pattern compared with EAS-6-B</CardTitle></CardHeader><CardContent><div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Evidence label="Structured Names" value={`${comparison.structuredRows} / ${comparison.sourceRows}`} /><Evidence label="Official level + area grammar" value={`${comparison.officialLocationGrammarRows} / ${comparison.structuredRows}`} /><Evidence label="Official classification codes" value={`${comparison.officialClassificationRows} / ${comparison.structuredRows}`} /><Evidence label="Listed drawing families" value={`${comparison.drawingRowsMatchingListedSheetFamilies} / ${comparison.drawingRows}`} /></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] border-separate border-spacing-0 text-left text-xs"><thead><tr>{['Pattern', 'Rows', 'Types', 'Segment 4 shape', 'Example', 'Official comparison'].map((label) => <th key={label} className="border-b bg-muted/50 px-3 py-2.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</th>)}</tr></thead><tbody>{comparison.patterns.map((pattern) => <tr key={pattern.pattern} className="align-top"><td className="border-b px-3 py-3 font-medium">{pattern.pattern}</td><td className="border-b px-3 py-3 font-mono">{pattern.count}</td><td className="border-b px-3 py-3 font-mono text-primary">{pattern.typeCodes.join(', ')}</td><td className="border-b px-3 py-3 text-muted-foreground">{pattern.numberShape}</td><td className="max-w-[290px] border-b px-3 py-3 font-mono text-[10px]">{pattern.example}</td><td className="max-w-[430px] border-b px-3 py-3 leading-5 text-muted-foreground">{pattern.comparison}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-5 text-muted-foreground">Five Procore Names contain an extra legacy suffix after the eight-segment core. The importer preserves the suffix verbatim instead of trying to split author-defined titles that may themselves contain hyphens.</p></CardContent></Card>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileLock2 className="size-4 text-primary" />Observed Procore numbering validators</CardTitle></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{procoreReference.numberingRules.map((rule) => <div key={`${rule.typeCode}-${rule.kind}-${rule.prefix}-${rule.width}`} className="rounded-lg border p-3"><div className="flex items-center justify-between"><span className="font-mono text-sm font-semibold text-primary">{rule.typeCode}</span><span className="text-[10px] text-muted-foreground">{rule.count} records</span></div><p className="mt-2 text-xs font-medium">{rule.kind === 'prefixed' ? `${rule.prefix}. + ${rule.width} digits` : rule.kind === 'numeric' ? `${rule.width}-digit number` : 'Literal value'}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">Example: {rule.examples[0]}</p></div>)}</div></CardContent></Card>

      <div className="grid gap-4 xl:grid-cols-2">{groups.map((group) => <MasterGroup key={group.title} {...group} />)}</div>
    </div>
  );
}

function SegmentChip({ segment }: { segment: Eas6bSegmentRule }) { return <div className="rounded-lg border border-primary/20 bg-primary/[0.04] px-3 py-2"><span className="block text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">Segment {segment.position}</span><span className="mt-0.5 block text-xs font-semibold">{segment.name}</span>{segment.sourceFields.length > 1 ? <span className="mt-1 block text-[9px] text-amber-700">Combined: {segment.sourceFields.join(' + ')}</span> : null}</div>; }
function MasterGroup({ title, description, items }: { title: string; description: string; items: ProcoreMasterCode[] }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="size-4 text-primary" />{title}</CardTitle><p className="text-xs text-muted-foreground">{description}</p></CardHeader><CardContent><div className="flex flex-wrap gap-2">{items.map((item) => <span key={item.code} className="inline-flex items-center gap-1.5 rounded-lg border bg-muted/30 px-2.5 py-1.5 text-xs"><span className="font-mono font-semibold text-primary">{item.code}</span><span className="text-muted-foreground">{item.label}</span><span className="rounded bg-background px-1 text-[9px] text-muted-foreground">{item.count}</span></span>)}</div></CardContent></Card>; }
function Evidence({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border bg-background p-3"><p className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 font-mono text-xs font-semibold">{value}</p></div>; }
