import { notFound } from 'next/navigation';

import { QualityRecordDetail } from '@/components/quality-records/quality-record-detail';
import { getV2Record } from '@/lib/services/quality-records';
import { createClient } from '@/lib/supabase/server';

export const dynamic = 'force-dynamic';
export default async function MirDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const client = await createClient(); const result = await getV2Record(client, 'mir_records', id); if (!result.data) notFound(); const r = result.data;
  return <QualityRecordDetail module="MIR" route="/mir" recordNumber={r.mir_number} documentCode={r.document_code} title={r.material_title} status={r.status} revision={r.revision} recordDate={r.record_date} discipline={r.discipline} location={r.installation_location} sections={[
    { title: 'Record identity and metadata', fields: [{ label: 'MIR number', value: r.mir_number }, { label: 'File type', value: r.file_type_code }, { label: 'Level / plan area', value: `${r.level_code ?? ''}${r.plan_area_code ?? ''}` }, { label: 'Volume', value: r.volume_code }, { label: 'Classification', value: r.classification_code }, { label: 'Originator', value: r.originator_code }, { label: 'Description', value: r.description, wide: true }] },
    { title: 'Material information', fields: [{ label: 'Supplier', value: r.supplier }, { label: 'Manufacturer', value: r.manufacturer }, { label: 'Supply reference', value: r.supply_reference }, { label: 'Delivery note', value: r.delivery_note_reference }, { label: 'Package / system', value: r.package_system }, { label: 'Work package', value: r.contractor_work_package }, { label: 'Approved quantity', value: r.approved_quantity }, { label: 'Quantity presented', value: r.quantity_presented }] },
    { title: 'Traceability and condition', fields: [{ label: 'Batch / heat / lot', value: r.batch_heat_lot_no }, { label: 'Serial / asset tag', value: r.serial_asset_tag }, { label: 'Delivery date', value: r.delivery_date }, { label: 'Shelf life / expiry', value: r.shelf_life_expiry }, { label: 'Storage / receipt condition', value: r.storage_receipt_condition, wide: true }, { label: 'Traceability mark / tag', value: r.traceability_mark_tag, wide: true }] },
    { title: 'References', fields: [{ label: 'Material submittal', value: r.material_submittal_reference }, { label: 'ITP', value: r.itp_reference }, { label: 'Specification', value: r.specification_reference }, { label: 'Approved drawing', value: r.approved_drawing_reference }, { label: 'Test certificate', value: r.test_certificate_reference }, { label: 'Manufacturer datasheet', value: r.manufacturer_datasheet_reference }] },
    { title: 'Inspection', fields: [{ label: 'Inspection findings', value: r.inspection_findings, wide: true }, { label: 'Required action / restriction', value: r.required_action_restriction, wide: true }] },
    { title: 'Review and material release', fields: [{ label: 'Reviewer', value: r.reviewer }, { label: 'Decision', value: r.review_decision }, { label: 'Final disposition', value: r.final_material_disposition }, { label: 'Closure date', value: r.closure_date }, { label: 'Review comments', value: r.review_comments, wide: true }, { label: 'Release basis', value: r.release_basis, wide: true }] },
    { title: 'Procore metadata', fields: [{ label: 'Procore reference', value: r.procore_reference }, { label: 'Workflow status', value: r.workflow_status }, { label: 'Current workflow step', value: r.current_workflow_step }, { label: 'Current assignees', value: r.current_step_assignees }, { label: 'Filename metadata only', value: r.source_filename, wide: true }] },
  ]} />; }
