import { notFound } from 'next/navigation';

import { QualityRecordDetail } from '@/components/quality-records/quality-record-detail';
import { RrrWorkspace } from '@/components/quality-records/rrr-workspace';
import { getRrrWorkspace, getV2Record } from '@/lib/services/quality-records';
import { createClient } from '@/lib/supabase/server';

export const dynamic = 'force-dynamic';
export default async function RrrDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const client = await createClient(); const [record, workspace] = await Promise.all([getV2Record(client, 'rrr_records', id), getRrrWorkspace(client, id)]); if (!record.data) notFound(); const r = record.data;
  return <QualityRecordDetail module="RRR" route="/rrr" recordNumber={r.record_number} documentCode={r.document_code} title={r.title} status={r.status} revision={r.submission_revision} recordDate={r.record_date} discipline={r.discipline} location={[r.level_code, r.grid, r.room].filter(Boolean).join(' · ')} sections={[
    { title: 'Controlled identity', fields: [{ label: 'Fixed CDE document code', value: r.document_code }, { label: 'SERBAN template code', value: r.template_code }, { label: 'Record number', value: r.record_number }, { label: 'Submission revision', value: r.submission_revision }, { label: 'Project phase', value: r.project_phase }, { label: 'Procore reference', value: r.procore_reference }] },
    { title: 'Room identification', fields: [{ label: 'Room / asset code', value: r.room_asset_code }, { label: 'Systems', value: r.systems }, { label: 'Requested by', value: r.requested_by }, { label: 'Request date', value: r.request_date }, { label: 'Related ITP', value: r.related_itp_reference }, { label: 'Employer readiness tracker', value: r.employer_readiness_checklist_tracker_ref }, { label: 'Readiness stage', value: r.readiness_stage }, { label: 'Room route', value: r.room_route }, { label: 'Equipment tag', value: r.equipment_tag }, { label: 'Level / plan area / volume', value: `${r.level_code ?? '—'}${r.plan_area_code ?? ''} / ${r.volume_code ?? '—'}` }] },
    { title: 'Inspection request and declaration', fields: [{ label: 'Requested date', value: r.requested_inspection_date }, { label: 'Requested time', value: r.requested_inspection_time }, { label: 'Notice given (working days)', value: r.notice_given_working_days }, { label: 'Purpose', value: r.inspection_purpose }, { label: 'Energization / power request ref.', value: r.energization_power_request_ref }, { label: 'Contractor declaration complete', value: r.declaration_complete }, { label: 'Room secured and controlled', value: r.room_secured_under_control }, { label: 'Doors installed and locked', value: r.doors_installed_locked }, { label: 'Authorized access retained', value: r.access_retained_by_authorized_person }, { label: 'Permit sleeve fitted', value: r.permit_sleeve_fitted }, { label: 'LOTO applied', value: r.loto_applied }, { label: 'Live warning notices fitted', value: r.live_warning_notices_fitted }, { label: 'Life-safety provisions in place', value: r.life_safety_provisions_in_place }, { label: 'Cleanliness / dust control maintained', value: r.cleanliness_dust_control_maintained }] },
    { title: 'Review and release', fields: [{ label: 'Engineer review', value: r.engineer_decision }, { label: 'Engineer name / date', value: `${r.engineer_name ?? 'Not provided'} / ${r.engineer_date ?? 'Not provided'}` }, { label: 'CxA gate', value: r.cxa_decision }, { label: 'CxA name / date', value: `${r.cxa_name ?? 'Not provided'} / ${r.cxa_date ?? 'Not provided'}` }, { label: 'Employer release', value: r.employer_release }, { label: 'Employer name / date', value: `${r.employer_name ?? 'Not provided'} / ${r.employer_date ?? 'Not provided'}` }, { label: 'Conditions / comments', value: r.conditions_comments, wide: true }, { label: 'Resubmission required', value: r.resubmission_required }, { label: 'Next RRR number', value: r.next_rrr_record_number }, { label: 'Next submission revision', value: r.next_submission_revision }] },
  ]}><RrrWorkspace rrr={r} workspace={workspace} /></QualityRecordDetail>; }
